version :  '3'

services :
    jce_java:
      build:  ./docker-jce-jre
      image:  cloud/jce_java
      read_only:  true
      command:  echo  "jce java"

    eureka:
      build:  ./cloud-eureka
      image:  cloud/eureka
      ports:
          - "8070:8070"
      depends_on:
          - "jce_java"

    config:
      build:  ./cloud-config
      image:  cloud/config
      ports:
          - "8090:8090"
      depends_on:
                - "jce_java"

    zuul:
      build:    ./cloud-zuul
      image:    cloud/zuul
      ports:
          -  "8091:8091"
      depends_on:
                - "jce_java"