server:
  port: 8090

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri:  'https://github.com/happilysheep/cloud-cloud.git'
          searchPaths: 'repo-config'
          username: 'happilysheep'
          password: 'Wangzj@926495'
eureka:
  client:
    service-url:
      defaultZone:  'http://localhost:8070/eureka'

encrypt:
  key: '*&3loa#@9no_0*(!'


