server:
  port: 8090

spring:
  application:
    name: sample-config
  cloud:
    config:
      server:
        git:
          uri:  'https://github.com/happilysheep/cloud-sample.git'
          searchPaths: 'config-repo'
          username: 'happilysheep'
          password: 'Wangzj@926495'
        encrypt:
                    enabled: false

